---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  labels:
    app: streamsheets
  name: streamsheets-installer
spec:
  tags:
  - name: "1.5"
    from:
      kind: DockerImage
      name: docker.io/cedalo/streamsheets-installer:1.5-linux
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Source
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  labels:
    app: streamsheets
  name: streamsheets
spec:
  tags:
  - name: "1.5"
    from:
      kind: DockerImage
      name: docker.io/cedalo/streamsheets:1.5
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Source
